### PR TITLE
fix: lenient mode skips invalid enum entries in collections and maps

### LINKED ISSUE #124: Lenient mode should skip invalid enum values in collections instead of throwing
## Summary

When parsing a `List<EnumType>` field with `Leniency.LENIENT`, an invalid enum
name in the YAML causes the whole `load()` to throw, instead of being skipped
with a warning. This breaks plugin startup on any user-edited config that
contains a stale or typo'd enum name — even if the rest of the config is
perfectly valid.

## Repro

```java
@YamlFile(lenient = Leniency.LENIENT)
public class Settings extends YamlFileInterface {
    @YamlKey("glider.mobs")
    public List<EntityType> gliderMobs = List.of(EntityType.CHICKEN);
}
```

```yaml
glider:
  mobs:
    - CHICKEN
    - FISH    # not a valid EntityType in modern Paper
```

`new Settings().load(file)` throws:

```
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.FISH
    at java.base/java.lang.Enum.valueOf(Enum.java:293)
    at org.avarion.yaml.TypeConverter.stringToEnum(TypeConverter.java:360)
    at org.avarion.yaml.TypeConverter.getConvertedValue(TypeConverter.java:58)
    at org.avarion.yaml.TypeConverter.convertWithType(TypeConverter.java:166)
    at org.avarion.yaml.TypeConverter.handleCollectionValue(TypeConverter.java:189)
    at org.avarion.yaml.TypeConverter.getConvertedValue(TypeConverter.java:62)
    at org.avarion.yaml.YamlFileInterface.readYamlKeyField(YamlFileInterface.java:205)
```

The exception bubbles all the way out of `load()`, so the calling plugin can't
recover individual fields — startup fails completely.

## Expected (under `Leniency.LENIENT`)

- Skip the invalid entry
- Continue with the remaining valid entries
- Optionally log a warning
- Don't throw

The current behaviour is correct for `Leniency.STRICT`, but lenient should be
forgiving of one bad entry the same way it's already forgiving of single-value
→ list coercion.

## Proposed change

In `TypeConverter.handleCollectionValue` (and the equivalent map-value path),
wrap the per-element conversion in a try/catch keyed off `isLenient`:

```java
for (Object item : collection) {
    try {
        result.add(convertWithType(elementType, item, isLenient));
    } catch (IllegalArgumentException ex) {
        if (!isLenient) throw ex;
        // log via your usual logger; entry is dropped under lenient mode
    }
}
```

Same idea for `handleMapValue` — skip key/value pairs whose key fails to
convert under lenient mode.

## Why this matters

Real-world configs accumulate stale enum names — Mojang renames between
Minecraft versions (`FISH` → `COD`/`SALMON`/`TROPICAL_FISH`), and users
typo. Strict failure disables the plugin entirely on otherwise-recoverable
user input. Lenient mode is the natural place to absorb that.

### PR DESCRIPTION
**Pull request by svaningelgem**
Closes #124.

## Summary

Under `Leniency.LENIENT`, an unknown enum constant inside a `List`/`Set`/`Queue` or as a `Map` key/value is now dropped instead of bubbling `IllegalArgumentException` out of `load()` and killing plugin startup. The valid surrounding entries are preserved.

`Leniency.STRICT` behaviour is unchanged: the original `IllegalArgumentException` still propagates for any unknown enum.

## Why scoped to enums (not all conversion failures)

Catching every `IllegalArgumentException` at the iterator level would silently swallow real bugs (bad UUIDs, bad numbers, etc.). The fix uses a private `LENIENT_ENUM_SKIP` sentinel returned only by `stringToEnum` when lenient + name unknown — collection/map iterators check that exact sentinel and skip just that entry. Other conversion failures still throw under both leniency modes.

## Top-level fields

A top-level enum field with a bad value under lenient now leaves the field at its declared default (consistent with collection skip behaviour). For `record` components the sentinel becomes `null` since a record component cannot be omitted.

## Test plan

- [x] New tests in `LeniencyTest` covering: list of enums (lenient skip / strict throw), map with bad enum value, map with bad enum key, top-level enum field (lenient default-fallback / strict throw), nested `List<List<Enum>>`, and a non-enum (UUID) failure that still surfaces under lenient.
- [x] Existing `testEnumerationsInvalidEnumItem` regression preserved by switching the shared `ListMaterial` fixture to `@YamlFile(lenient = STRICT)` — the test still verifies "bad enum in list must throw", just in strict mode where that behaviour still holds.
- [x] Full suite: 217 tests, all green.

### CODE REVIEW

File: src/test/java/org/avarion/yaml/testClasses/ListMaterial.java [hunk 1]
```diff
@@ -1,11 +1,14 @@
...
 
+import org.avarion.yaml.Leniency;
+import org.avarion.yaml.YamlFile;
 import org.avarion.yaml.YamlFileInterface;
 import org.avarion.yaml.YamlKey;
 
 import java.util.Arrays;
 import java.util.List;
 
+@YamlFile(lenient = Leniency.STRICT)
```
Comment (svaningelgem) [inline src/test/java/org/avarion/yaml/testClasses/ListMaterial.java]: This is changing a LOT of other tests. If you want to test this: create a different class specifically tuned for ENUM's.

File: src/test/java/org/avarion/yaml/LeniencyTest.java
Comment (svaningelgem) [inline src/test/java/org/avarion/yaml/LeniencyTest.java:1]: Those are too many tests in my opinion for just testing leniency on enums?

File: src/test/java/org/avarion/yaml/testClasses/ListMaterial.java (hunk 1 above)
Comment (svaningelgem) [reply src/test/java/org/avarion/yaml/testClasses/ListMaterial.java]: Reverted ListMaterial to its original shape. Added a new StrictListMaterial fixture (@YamlFile(lenient = STRICT)) used only by testEnumerationsInvalidEnumItem; the other two ListMaterial-using tests are unchanged.

File: src/test/java/org/avarion/yaml/LeniencyTest.java
Comment (svaningelgem) [reply src/test/java/org/avarion/yaml/LeniencyTest.java:1]: Trimmed from 8 to 3: lenient list-skip (the issue's exact scenario), lenient map-value-skip, and one guard-rail asserting lenient still throws on non-enum conversion failures (UUID). Dropped the top-level, nested-list, map-key, and strict-counterpart tests.
